In [89]:
#files to open: train and test data,

from google.colab import files

uploaded = files.upload()


Saving train_y1_v8.csv to train_y1_v8.csv


# Imports and functions

In [0]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

from sklearn.utils import class_weight
from sklearn.metrics import recall_score, precision_score, confusion_matrix

In [5]:
import numpy as np
from keras.models import Model
from keras.layers import Dense, Input, Dropout, LSTM, Activation

Using TensorFlow backend.


In [0]:
import matplotlib.pyplot as plt
%matplotlib inline

def plot_loss(epochs, loss, val_loss):
    plt.figure(figsize=(10, 7))
    plt.plot(np.arange(epochs), loss, label='loss')
    plt.plot(np.arange(epochs), val_loss, label='val_loss')
    plt.legend()
    plt.grid(True)
def acc_graph(epochs, train_acc, val_acc):
    x_axis = np.linspace(1, epochs, num=epochs)
    
    plt.figure(figsize=(10, 7))
    plt.plot(x_axis, train_acc, color='g', lw=3, alpha=0.7, label='Train Accuracy')
    plt.plot(x_axis, val_acc, color='orange', lw=3, alpha=0.7, label='Val Accuracy')
    plt.title('Accuracy graph')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend(loc='lower right')
    plt.grid(True)

In [0]:
def calculation_classes(y, y_test = None):
    print ('\t\tTRAIN DATA\tTEST DATA')
    print ('Negative\t', np.sum(y==0),'  ',
           round(100*np.sum(y==0)/y.shape[0],2),'%',
           '\t',np.sum(y_test==0),'  ',
           round(100*np.sum(y_test==0)/y_test.shape[0],2),'%'
           '\nPositive\t ', np.sum(y==1),' ',
           round(100*np.sum(y==1)/y.shape[0],2),'%'
           '\t',np.sum(y_test==1),' ',
           round(100*np.sum(y_test==1)/y_test.shape[0],2),'%'
      )

In [0]:
#from utils import model

In [0]:
def scale_0_1_for_samples(X):
  mm = MinMaxScaler()

  for i in range(X.shape[0]):
    line = X[i]
    #print(line)
  
    line = line.reshape(-1, 1)
    X[i] = mm.fit_transform(line).reshape(1,-1)
  return X
 
def scale_standard_for_1sample(X):
  ss = StandardScaler()

  for i in range(X.shape[0]):
    line = X[i]
    X[i] = ss.fit_transform(line.reshape(-1,1)).reshape(1,-1)
  return X

def scale_substraction_mean_for_1sample(X):
  for i in range(X.shape[0]):
    line = X[i]
    #print(line)
    mean = np.mean(line)
    #print(mean)
    X[i] = line - mean
    #print(X[i])
    
  return X
    

In [0]:
def get_mean_for_features(X):
  m = X.shape[0]
  X_mean = np.zeros((m,1))
  for i in range(m):
    X_mean[i] = np.mean(X[i,:], axis=0)
  return X_mean

def scale_standard_for_samples(X, X_mean):
  ss = StandardScaler()
  ss.fit(X_mean)

  X = ss.transform(X)
  return X

In [0]:
def make_predictions(X, y, model, X_ini,out=False,):
  preds = model.predict(X)
  y_predict = np.where(preds > 0.5, 1, 0)
  recall = recall_score(y, y_predict)
  print('Recall = ', recall, 'Precision = ', precision_score(y, y_predict))
  cm  = confusion_matrix(y, y_predict)
  print(cm)
  if out is True:
    for i in range(X.shape[0]):
      if abs(y_predict[i] - y[i])!= 0:
        print(y[i], preds[i], X_ini[i], np.ndarray.tolist(X[i]))
    

# Import data sets

In [0]:
#data_train = pd.read_csv('sources/train.csv')
#data_test = pd.read_csv('sources/test_v7_v8.csv')

data1_train = pd.read_csv('train_y1_v8.csv')
data0_train = pd.read_csv('train_y0_v8.csv')

X = np.vstack((data1_train.drop(['Y'], axis='columns').values, data0_train.drop(['Y'], axis='columns').values))

y = np.hstack((data1_train['Y'].values, data0_train['Y'].values))
X_ini = X.copy()

In [0]:
data_add = pd.read_csv('train_0_change_1_to_close.csv')

X_add = data_add.drop(['Y'], axis='columns').values
y_add = data_add['Y'].values

X = np.vstack((X, X_add))
y = np.hstack((y, y_add))

In [0]:
data_v4 = pd.read_csv('train_0_v4.csv')

X_add = data_add.drop(['Y'], axis='columns').values
y_add = data_add['Y'].values

X = np.vstack((X, X_add))
y = np.hstack((y, y_add))

In [0]:
scale_X = scale_substraction_mean_for_1sample

In [190]:
X = scale_X(X)

X_train,X_dev,y_train,y_dev = train_test_split(X, y, test_size=0.2, \
                                               shuffle=True, stratify=y)

class_weights_train = class_weight.compute_class_weight('balanced',
                                                 np.unique(y_train),
                                                 y_train)
class_weights = class_weight.compute_class_weight('balanced',
                                                 np.unique(y), y)
print(class_weights)
print(class_weights[0]/(class_weights[1]+class_weights[0]))
calculation_classes(y, y_dev)

X = np.expand_dims(X, axis=2)
X_train = np.expand_dims(X_train, axis=2)
X_dev = np.expand_dims(X_dev, axis=2)

[0.5518884  5.31803279]
0.09401972872996302
		TRAIN DATA	TEST DATA
Negative	 70536    90.6 % 	 14108    90.6 %
Positive	  7320   9.4 %	 1464   9.4 %


In [0]:
data_v4_test = pd.read_csv('test_v4_7615.csv')
X_v4 = data_v4_test.drop(['Y'], axis='columns').values
y_v4 = data_v4_test['Y'].values
test_v4 =  data_v4_test.drop(['Y'], axis='columns').values

X_v4 = scale_X(X_v4)
X_v4 = np.expand_dims(X_v4, axis=2)

In [0]:
data_v7v8 = pd.read_csv('test_v7_v8.csv')

X_v7v8 = data_v7v8.drop(['Y'], axis='columns').values
test_v7v8 =  data_v7v8.drop(['Y'], axis='columns').values
y_v7v8 = data_v7v8['Y'].values

X_v7v8 = scale_X(X_v7v8)
X_v7v8 = np.expand_dims(X_v7v8, axis=2)

In [0]:
#data_test = pd.read_csv('sources/test_v3.csv')
data_v3 = pd.read_csv('test_v3.csv')

X_v3 = data_v3.drop(['Y'], axis='columns').values
test_v3 =  data_v3.drop(['Y'], axis='columns').values
y_v3 = data_v3['Y'].values

X_v3 = scale_X(X_v3)
X_v3 = np.expand_dims(X_v3, axis=2)

# NN on train/dev sets

In [0]:
from keras.models import Model, Sequential
from keras.layers import Dense, Input, GRU, LSTM
from keras.optimizers import Adam
from keras.callbacks import LearningRateScheduler


def model_GRU(input_shape, Ty, hidden_size):
    i = Input(shape=input_shape, dtype='float32')
    X = GRU(hidden_size, return_sequences=False)(i)
    
    X = Dense(Ty, activation='sigmoid')(X)
    model = Model(inputs=[i], outputs=X)
    
    return model
  
def model_LSTM(hidden_size):  
  model = Sequential()
  model.add(LSTM(hidden_size, return_sequences=False, input_shape=(Tx,1)))
  model.add(Dense(units=1, activation='sigmoid'))
  
  return model


In [165]:
# For ready model
'''GRU_model = model_GRU((Tx,1),Ty)#LSTM_model.summary()
GRU_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


GRU_model.load_weights('GRU_sequence_weights.h5')'''

"GRU_model = model_GRU((Tx,1),Ty)#LSTM_model.summary()\nGRU_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])\n\n\nGRU_model.load_weights('GRU_sequence_weights.h5')"

In [0]:
Tx=  6
Ty = 1
epochs = 5
batch_size = 32

In [192]:
GRU_model = model_LSTM(16)
opt = Adam(lr=0.02, beta_1=0.9, beta_2=0.999)
GRU_model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])
logs = GRU_model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, shuffle=True,\
                    validation_data=(X_dev, y_dev), verbose=2, class_weight=class_weights_train, \
                    initial_epoch=0)

Train on 62284 samples, validate on 15572 samples
Epoch 1/5
 - 11s - loss: 0.1940 - acc: 0.9396 - val_loss: 0.0246 - val_acc: 0.9967
Epoch 2/5
 - 8s - loss: 0.0212 - acc: 0.9930 - val_loss: 0.0132 - val_acc: 0.9943
Epoch 3/5
 - 8s - loss: 0.0148 - acc: 0.9959 - val_loss: 0.0100 - val_acc: 0.9970
Epoch 4/5
 - 8s - loss: 0.0100 - acc: 0.9972 - val_loss: 0.0126 - val_acc: 0.9969
Epoch 5/5
 - 8s - loss: 0.0102 - acc: 0.9971 - val_loss: 0.0112 - val_acc: 0.9958


In [0]:
opt = Adam(lr=0.01, beta_1=0.9, beta_2=0.999, decay=0.0005)
GRU_model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])

In [196]:
n_epochs = 1
logs = GRU_model.fit(X_train, y_train , epochs=n_epochs, batch_size=batch_size, shuffle=True,\
                    validation_data=(X_dev, y_dev), verbose=2, class_weight=class_weights_train)

Train on 62284 samples, validate on 15572 samples
Epoch 1/1
 - 8s - loss: 5.2782e-04 - acc: 0.9999 - val_loss: 4.1907e-04 - val_acc: 0.9999


In [197]:
make_predictions(X,y, GRU_model,X_ini, out=False)

Recall =  1.0 Precision =  0.9993174061433447
[[70531     5]
 [    0  7320]]


In [0]:
#make_predictions(X_dev,y_dev, out=True, model=GRU_model)

In [198]:
make_predictions(X_v7v8, y_v7v8, out=True, model=GRU_model, X_ini=test_v7v8)

Recall =  1.0 Precision =  1.0
[[13  0]
 [ 0 46]]


In [199]:
make_predictions(X_v3, y_v3, out=True, model=GRU_model, X_ini=test_v3)

Recall =  0.9811320754716981 Precision =  0.8524590163934426
[[33  9]
 [ 1 52]]
0.0 [0.64055765] [-0.377 -0.231 -0.2   -0.155  0.027  0.208] [[-0.25566666666666665], [-0.10966666666666668], [-0.07866666666666668], [-0.033666666666666664], [0.14833333333333334], [0.32933333333333337]]
0.0 [0.88283145] [-0.377 -0.231 -0.2   -0.155  0.027  0.227] [[-0.2588333333333333], [-0.11283333333333333], [-0.08183333333333333], [-0.036833333333333315], [0.1451666666666667], [0.3451666666666667]]
0.0 [0.92472976] [-0.377 -0.231 -0.2   -0.155  0.027  0.242] [[-0.2613333333333333], [-0.11533333333333333], [-0.08433333333333333], [-0.03933333333333332], [0.1426666666666667], [0.3576666666666667]]
0.0 [0.9648842] [-0.377 -0.231 -0.2   -0.155  0.027  0.261] [[-0.2645], [-0.11850000000000001], [-0.08750000000000001], [-0.042499999999999996], [0.1395], [0.3735]]
0.0 [0.9904851] [-0.377 -0.231 -0.2   -0.155  0.027  0.279] [[-0.2675], [-0.12150000000000001], [-0.09050000000000001], [-0.0455], [0.1365], [0.388

In [200]:
make_predictions(X_v4, y_v4, out=True, model=GRU_model, X_ini=test_v4)

Recall =  0.0 Precision =  0.0
[[10 61]
 [ 0  0]]
0.0 [1.] [-0.493 -0.476 -0.335 -0.11   0.023  0.169] [[-0.28933333333333333], [-0.2723333333333333], [-0.13133333333333333], [0.09366666666666669], [0.22666666666666668], [0.3726666666666667]]
0.0 [0.9999999] [-0.493 -0.476 -0.335 -0.11   0.059  0.169] [[-0.29533333333333334], [-0.2783333333333333], [-0.13733333333333334], [0.08766666666666668], [0.2566666666666667], [0.3666666666666667]]
0.0 [0.9999998] [-0.493 -0.447 -0.335 -0.11   0.059  0.169] [[-0.3001666666666667], [-0.25416666666666665], [-0.1421666666666667], [0.08283333333333333], [0.25183333333333335], [0.36183333333333334]]
0.0 [0.9999997] [-0.493 -0.447 -0.335 -0.11   0.139  0.169] [[-0.3135], [-0.2675], [-0.15550000000000003], [0.06949999999999999], [0.3185], [0.3485]]
0.0 [1.] [-0.493 -0.447 -0.302 -0.11   0.023  0.169] [[-0.29966666666666664], [-0.25366666666666665], [-0.10866666666666663], [0.08333333333333336], [0.21633333333333335], [0.36233333333333334]]
0.0 [1.] [-0.

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples.
  'recall', 'true', average, warn_for)


In [0]:
#make_predictions(X_add, y_add, out=True, model=GRU_model, X_ini=X_ini_add)

In [0]:
#plot_loss(epochs, logplot_loss(epos.history.get('loss'), logs.history.get('val_loss'))

In [0]:
#acc_graph(epochs, logs.history.get('acc'), logs.history.get('val_acc'))

In [0]:
GRU_model.save_weights('LSTM_sequence_weights.h5')

In [0]:
files.download('LSTM_sequence_weights.h5')

In [0]:
LSTM_model = model((Tx,1),Ty)
#LSTM_model.summary()
LSTM_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
logs = LSTM_model.fit(X_train, y_train , epochs=epochs, batch_size=batch_size, shuffle=True,\
               validation_data=(X_dev, y_dev), verbose=0, class_weight=class_weights_train)

# Final fit NN on all train set

In [0]:
Tx=  6
Ty = 1
epochs = 250
batch_size = 32

In [0]:
LSTM_model = model((Tx,1),Ty)
#LSTM_model.summary()
LSTM_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
LSTM_model.fit(X, y , epochs=epochs, batch_size=batch_size, shuffle=True,\
               verbose=0, class_weight=class_weights)
LSTM_model.save_weights('sources/LSTM_sequence_weights.h5')

In [0]:
print(LSTM_model.summary())
test_preds = LSTM_model.predict(X_test)

In [0]:
for i in range(X_test.shape[0]):
    if test_preds[i] > 0.5:
        print(i)

In [0]:
LSTM_model = model((Tx,1),Ty)
LSTM_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

LSTM_model.load_weights('LSTM_sequence_weights.h5')

In [0]:
test_preds = LSTM_model.predict(X_test)

for i in range(X_test.shape[0]):
    if test_preds[i] > 0.5:
        print(i)